### ISSUE TITLE
smartcard.reader.ReaderFactory.ReaderFactory.readers(groups) is giving the empty list

### ISSUE THREAD

**Issue by kalyank23** [LudovicRousseau/pyscard#125]
#### Your system information

* Operating system used: Windows 10
* pyscard version: 2.0.1
* Python version: 3.9

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen.
"smartcard.reader.ReaderFactory.ReaderFactory.readers(groups)" method should return the list of readers

Describe what _did_ happen.
"smartcard.reader.ReaderFactory.ReaderFactory.readers(groups)" method returning empty list intermittently

#### Steps for reproducing this issue:

1. Connect the Yubikey token
2. Run the below command multiple times.
from smartcard import System
print(System.readers())

3. Verify that it wont print [] always 

We are seeing the below in event viewer logs of that system sometimes, will that be a problem?

![image](https://user-images.githubusercontent.com/34736945/154036850-dc0383cd-0d57-4b56-a369-3ffaf2db28bc.png)

But the working machines and this machine also has the same services status in control panel

![image](https://user-images.githubusercontent.com/34736945/154037017-34b5a7bf-5679-4820-9b0c-777191cbf6a4.png)

Do we need to start that "Smart Card Device Enumeration Service"?

**Comment by LudovicRousseau** [comment]
First, I suggest to upgrade your pyscard to version 2.0.2

I would suspect a problem in Windows PC/SC layer.
I do not use Windows so I can't really help. You would need a tool to spy the Windows WinSCard answers to check if the empty list comes from Windows itself or is a bug in pyscard.

**Comment by antonio-fr** [comment]
Very weird behavior. Check twice that you are running v2.0.1 as you declare. Because from what I can think about, this issue really [looks like this one](https://github.com/LudovicRousseau/pyscard/issues/123), affecting v2.0.2. The effect is that it returns an empty reader list in some conditions, and this is what you observe. The 2.0.2 version has an issue in Windows when the last reader is disconnected, any new reader connected is not found. This was fixed recently and will be ok in the next release. There is not known issue to me in v2.0.1 in Windows.

**Comment by LudovicRousseau** [comment]
Try again with PySCard version 2.0.3 I just released.

**Comment by LudovicRousseau** [comment]
Does version 2.0.3 solves the problem?

**Comment by LudovicRousseau** [comment]
In your sample code `smartcard.reader.ReaderFactory.ReaderFactory.readers(groups)` what is the value of the `groups` variable?

**Comment by LudovicRousseau** [comment]
No feedback since 1 year.
Closing.
